{"elemID":"component_443","date":"6/5/2020","time":"12:00am","name":"summary","pathname":"summary","pathstr":"async.forever~summary","path":[["/","async"],[".","forever"],["~","summary"]],"flags":[],"source":[["/","async"],[".","forever"]],"sourcestr":"async.forever","superClasses":[],"interfaces":[],"satisfies":[],"ctype":"spare","valtype":[],"isKwarg":false,"isMultiArg":false,"isSpare":true,"isModule":false,"isClass":false,"simpleCtype":"spare","hideCtype":false,"spares":[],"modules":[],"enums":[],"statics":[],"functions":[],"members":[],"methods":[],"localValues":[],"localFunctions":[],"arguments":[],"finalArgs":[],"finalKwargs":[],"returns":[],"throws":[],"names":[],"events":[],"signatures":[],"propertySymbols":[],"memberSymbols":[],"returnsSymbols":[],"hasChildren":true,"isTotallyEmpty":false,"doc":[{"doc":"\n\nCalls the asynchronous function `fn` with a callback parameter that allows it\nto call itself again, in series, indefinitely.\n\nIf an error is passed to the\ncallback then `errback` is called with the error, and execution stops,\notherwise it will never be called.\n\nthis function will be called, and execution stops. Invoked with (err).\n\n### Example\n```javascript\n\nasync.forever(\n    function(next) {\n        // next is suitable for passing to things that need a callback(err [, whatever]);\n        // it will result in this function being called again.\n    },\n    function(err) {\n        // if next is called with a value in its first parameter, it will appear\n        // in here as 'err', and execution will stop.\n    }\n);\n\n```\n\n","context":[]}],"breadcrumbs":[{"path":[["/","async"]],"name":"async","delimiter":"/"},{"path":[["/","async"],[".","forever"]],"name":"forever","delimiter":"."},{"path":[["/","async"],[".","forever"],["~","summary"]],"name":"summary","delimiter":"~"}],"sanitaryName":"summary_1","baseTagPath":"../../../../../../"}
